<?php

namespace ContainerP00Wcts;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RCKF0aQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rCKF0aQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rCKF0aQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'command' => ['privates', '.errored..service_locator.rCKF0aQ.App\\Entity\\Posts\\UseCase\\CreatePost\\Command', NULL, 'Cannot autowire service ".service_locator.rCKF0aQ": it references class "App\\Entity\\Posts\\UseCase\\CreatePost\\Command" but no such service exists.'],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'command' => 'App\\Entity\\Posts\\UseCase\\CreatePost\\Command',
            'mailer' => '?',
        ]);
    }
}
