<?php

namespace ContainerP00Wcts;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X_OS9pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x.OS9p_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x.OS9p_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'command' => ['privates', '.errored..service_locator.x.OS9p_.App\\Entity\\Likes\\UseCase\\unlike\\Command', NULL, 'Cannot autowire service ".service_locator.x.OS9p_": it references class "App\\Entity\\Likes\\UseCase\\unlike\\Command" but no such service exists.'],
        ], [
            'command' => 'App\\Entity\\Likes\\UseCase\\unlike\\Command',
        ]);
    }
}
