<?php

namespace ContainerP00Wcts;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OpXxxFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.opXxx_f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.opXxx_f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'post' => ['privates', '.errored..service_locator.opXxx_f.App\\Entity\\Posts\\Post', NULL, 'Cannot autowire service ".service_locator.opXxx_f": it references class "App\\Entity\\Posts\\Post" but no such service exists.'],
        ], [
            'post' => 'App\\Entity\\Posts\\Post',
        ]);
    }
}
