<?php

namespace ContainerP00Wcts;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLikesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Adapter\Like\Likes' shared autowired service.
     *
     * @return \App\Adapter\Like\Likes
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Likes/ReadModel/LikesQueryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Adapter/Like/Likes.php';

        return $container->services['App\\Adapter\\Like\\Likes'] = new \App\Adapter\Like\Likes(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
