<?php

namespace ContainerP00Wcts;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPost3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.opXxx_f.App\Entity\Posts\Post' shared service.
     *
     * @return \App\Entity\Posts\Post
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.opXxx_f": it references class "App\\Entity\\Posts\\Post" but no such service exists.');
    }
}
