<?php

namespace ContainerP00Wcts;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDeleteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\newsletters\UserDeleteController' shared autowired service.
     *
     * @return \App\Controller\newsletters\UserDeleteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/newsletters/UserDeleteController.php';
        include_once \dirname(__DIR__, 4).'/src/Entity/Newsletter/NewslettersInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Adapter/Newsletter/Newsletters.php';

        $container->services['App\\Controller\\newsletters\\UserDeleteController'] = $instance = new \App\Controller\newsletters\UserDeleteController(new \App\Adapter\Newsletter\Newsletters(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService())));

        $instance->setContainer(($container->privates['.service_locator.0QcI221'] ?? $container->load('get_ServiceLocator_0QcI221Service'))->withContext('App\\Controller\\newsletters\\UserDeleteController', $container));

        return $instance;
    }
}
