<?php

namespace ContainerP00Wcts;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnlikeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Entity\Likes\UseCase\unlike' shared autowired service.
     *
     * @return \App\Entity\Likes\UseCase\unlike
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Entity/Likes/UseCase/unlike.php';

        $container->services['App\\Entity\\Likes\\UseCase\\unlike'] = $instance = new \App\Entity\Likes\UseCase\unlike(($container->services['application_like'] ?? $container->load('getApplicationLikeService')), ($container->services['doctrine_application_transaction'] ?? $container->load('getDoctrineApplicationTransactionService')));

        $instance->setContainer(($container->privates['.service_locator.0QcI221'] ?? $container->load('get_ServiceLocator_0QcI221Service'))->withContext('App\\Entity\\Likes\\UseCase\\unlike', $container));

        return $instance;
    }
}
