<?php

namespace ContainerP00Wcts;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserJoinControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\newsletters\UserJoinController' shared autowired service.
     *
     * @return \App\Controller\newsletters\UserJoinController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/newsletters/UserJoinController.php';

        $container->services['App\\Controller\\newsletters\\UserJoinController'] = $instance = new \App\Controller\newsletters\UserJoinController();

        $instance->setContainer(($container->privates['.service_locator.0QcI221'] ?? $container->load('get_ServiceLocator_0QcI221Service'))->withContext('App\\Controller\\newsletters\\UserJoinController', $container));

        return $instance;
    }
}
