<?php

namespace ContainerKQl7tq1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3CprBVbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3CprBVb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3CprBVb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'command' => ['privates', '.errored..service_locator.3CprBVb.App\\Entity\\Posts\\UseCase\\CreatePost\\Command', NULL, 'Cannot autowire service ".service_locator.3CprBVb": it references class "App\\Entity\\Posts\\UseCase\\CreatePost\\Command" but no such service exists.'],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'newsletter' => ['privates', '.errored..service_locator.3CprBVb.App\\Entity\\Newsletter\\Newsletter', NULL, 'Cannot autowire service ".service_locator.3CprBVb": it references class "App\\Entity\\Newsletter\\Newsletter" but no such service exists.'],
        ], [
            'command' => 'App\\Entity\\Posts\\UseCase\\CreatePost\\Command',
            'mailer' => '?',
            'newsletter' => 'App\\Entity\\Newsletter\\Newsletter',
        ]);
    }
}
