<?php

namespace ContainerKQl7tq1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4tO0bWIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4tO0bWI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4tO0bWI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'User' => ['services', 'App\\Adapter\\User\\Users', 'getUsersService', true],
            'activateUser' => ['services', 'App\\Entity\\Users\\UseCase\\ActivateUser', 'getActivateUserService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'user' => ['privates', '.errored..service_locator.4tO0bWI.App\\Entity\\Users\\User', NULL, 'Cannot autowire service ".service_locator.4tO0bWI": it references class "App\\Entity\\Users\\User" but no such service exists.'],
        ], [
            'User' => 'App\\Adapter\\User\\Users',
            'activateUser' => 'App\\Entity\\Users\\UseCase\\ActivateUser',
            'mailer' => '?',
            'user' => 'App\\Entity\\Users\\User',
        ]);
    }
}
