<?php

namespace ContainerKQl7tq1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LN3OQw_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LN3OQw.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LN3OQw.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'createPost' => ['services', 'App\\Entity\\Posts\\UseCase\\CreatePost', 'getCreatePostService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'newsletter' => ['privates', '.errored..service_locator.LN3OQw..App\\Entity\\Newsletter\\Newsletter', NULL, 'Cannot autowire service ".service_locator.LN3OQw.": it references class "App\\Entity\\Newsletter\\Newsletter" but no such service exists.'],
        ], [
            'createPost' => 'App\\Entity\\Posts\\UseCase\\CreatePost',
            'mailer' => '?',
            'newsletter' => 'App\\Entity\\Newsletter\\Newsletter',
        ]);
    }
}
