<?php

namespace ContainerKQl7tq1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UgyrBnkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ugyrBnk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ugyrBnk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'id' => ['privates', '.errored..service_locator.ugyrBnk.App\\Entity\\Posts\\Post', NULL, 'Cannot autowire service ".service_locator.ugyrBnk": it references class "App\\Entity\\Posts\\Post" but no such service exists.'],
            'postsQuery' => ['privates', 'App\\Adapter\\Post\\PostsQuery', 'getPostsQueryService', true],
        ], [
            'id' => 'App\\Entity\\Posts\\Post',
            'postsQuery' => 'App\\Adapter\\Post\\PostsQuery',
        ]);
    }
}
