<?php

namespace ContainerKQl7tq1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3CprBVb.App\Entity\Posts\UseCase\CreatePost\Command' shared service.
     *
     * @return \App\Entity\Posts\UseCase\CreatePost\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.3CprBVb": it references class "App\\Entity\\Posts\\UseCase\\CreatePost\\Command" but no such service exists.');
    }
}
