<?php

namespace ContainerKQl7tq1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsletter2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.L8FURQc.App\Entity\Newsletter\Newsletter' shared service.
     *
     * @return \App\Entity\Newsletter\Newsletter
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.L8FURQc": it references class "App\\Entity\\Newsletter\\Newsletter" but no such service exists.');
    }
}
