<?php

namespace ContainerKQl7tq1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewslettersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Adapter\Newsletter\Newsletters' shared autowired service.
     *
     * @return \App\Adapter\Newsletter\Newsletters
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\src\\Entity\\Newsletter\\NewslettersInterface.php';
        include_once \dirname(__DIR__, 4).'\\src\\Adapter\\Newsletter\\Newsletters.php';

        return $container->privates['App\\Adapter\\Newsletter\\Newsletters'] = new \App\Adapter\Newsletter\Newsletters(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
