<?php

namespace ContainerKQl7tq1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDeleteNewsletterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Entity\Newsletter\Newsletters\UseCase\UserDeleteNewsletter' shared autowired service.
     *
     * @return \App\Entity\Newsletter\Newsletters\UseCase\UserDeleteNewsletter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
        include_once \dirname(__DIR__, 4).'\\src\\Entity\\Newsletter\\Newsletters\\UseCase\\UserDeleteNewsletter.php';

        $container->services['App\\Entity\\Newsletter\\Newsletters\\UseCase\\UserDeleteNewsletter'] = $instance = new \App\Entity\Newsletter\Newsletters\UseCase\UserDeleteNewsletter(($container->services['application_Newsletter'] ?? $container->load('getApplicationNewsletterService')), ($container->services['doctrine_application_transaction'] ?? $container->load('getDoctrineApplicationTransactionService')));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Entity\\Newsletter\\Newsletters\\UseCase\\UserDeleteNewsletter', $container));

        return $instance;
    }
}
