<?php

namespace ContainerU3xIjYg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AOLTLWkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aOLTLWk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aOLTLWk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'id' => ['privates', '.errored..service_locator.aOLTLWk.App\\Entity\\Posts\\Post', NULL, 'Cannot autowire service ".service_locator.aOLTLWk": it references class "App\\Entity\\Posts\\Post" but no such service exists.'],
            'likes' => ['services', 'App\\Adapter\\Like\\Likes', 'getLikesService', true],
            'unlike' => ['privates', '.errored..service_locator.aOLTLWk.App\\Entity\\Likes\\UseCase\\unlike', NULL, 'Cannot autowire service ".service_locator.aOLTLWk": it references class "App\\Entity\\Likes\\UseCase\\unlike" but no such service exists.'],
        ], [
            'id' => 'App\\Entity\\Posts\\Post',
            'likes' => 'App\\Adapter\\Like\\Likes',
            'unlike' => 'App\\Entity\\Likes\\UseCase\\unlike',
        ]);
    }
}
