<?php

namespace ContainerU3xIjYg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5IH9RaeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5IH9Rae' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5IH9Rae'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'createComment' => ['services', 'App\\Entity\\Comments\\UseCase\\CreateComment', 'getCreateCommentService', true],
            'id' => ['privates', '.errored..service_locator.5IH9Rae.App\\Entity\\Posts\\Post', NULL, 'Cannot autowire service ".service_locator.5IH9Rae": it references class "App\\Entity\\Posts\\Post" but no such service exists.'],
        ], [
            'createComment' => 'App\\Entity\\Comments\\UseCase\\CreateComment',
            'id' => 'App\\Entity\\Posts\\Post',
        ]);
    }
}
