<?php

namespace ContainerU3xIjYg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnlikeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aOLTLWk.App\Entity\Likes\UseCase\unlike' shared service.
     *
     * @return \App\Entity\Likes\UseCase\unlike
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.aOLTLWk": it references class "App\\Entity\\Likes\\UseCase\\unlike" but no such service exists.');
    }
}
