<?php

namespace Container1AX8EFf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommand2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TdR_qZ1.App\Entity\Posts\UseCase\CreatePost\Command' shared service.
     *
     * @return \App\Entity\Posts\UseCase\CreatePost\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.TdR_qZ1": it references class "App\\Entity\\Posts\\UseCase\\CreatePost\\Command" but no such service exists.');
    }
}
