<?php

namespace ContainerX73HebA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A7shXJhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A7shXJh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A7shXJh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'User' => ['services', 'App\\Adapter\\User\\Users', 'getUsersService', true],
            'createUser' => ['services', 'App\\Entity\\Users\\UseCase\\CreateUser', 'getCreateUserService', true],
            'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
        ], [
            'User' => 'App\\Adapter\\User\\Users',
            'createUser' => 'App\\Entity\\Users\\UseCase\\CreateUser',
            'passwordEncoder' => '?',
        ]);
    }
}
