<?php

namespace ContainerX73HebA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnonJoinTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Newsletter\AnonJoinType' shared autowired service.
     *
     * @return \App\Form\Newsletter\AnonJoinType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\AbstractType.php';
        include_once \dirname(__DIR__, 4).'\\src\\Form\\Newsletter\\AnonJoinType.php';

        return $container->privates['App\\Form\\Newsletter\\AnonJoinType'] = new \App\Form\Newsletter\AnonJoinType();
    }
}
