<?php

namespace ContainerX73HebA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommand6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lEPEAjr.App\Entity\Users\UseCase\PasswordChangeUser\Command' shared service.
     *
     * @return \App\Entity\Users\UseCase\PasswordChangeUser\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.lEPEAjr": it references class "App\\Entity\\Users\\UseCase\\PasswordChangeUser\\Command" but no such service exists.');
    }
}
