<?php

namespace ContainerX73HebA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommand4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.apuLg5r.App\Entity\Newsletter\Newsletters\UseCase\AnonJoinNewsletter\Command' shared service.
     *
     * @return \App\Entity\Newsletter\Newsletters\UseCase\AnonJoinNewsletter\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.apuLg5r": it references class "App\\Entity\\Newsletter\\Newsletters\\UseCase\\AnonJoinNewsletter\\Command" but no such service exists.');
    }
}
