<?php

namespace ContainerX73HebA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsletterControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\newsletters\NewsletterController' shared autowired service.
     *
     * @return \App\Controller\newsletters\NewsletterController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
        include_once \dirname(__DIR__, 4).'\\src\\Entity\\Newsletter\\Newsletters\\UseCase\\AnonJoinNewsletter\\Responder.php';
        include_once \dirname(__DIR__, 4).'\\src\\Controller\\newsletters\\NewsletterController.php';

        $container->services['App\\Controller\\newsletters\\NewsletterController'] = $instance = new \App\Controller\newsletters\NewsletterController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\newsletters\\NewsletterController', $container));

        return $instance;
    }
}
