<?php

namespace ContainerXgjj4d9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZxEonKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._zxEonK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._zxEonK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'createComment' => ['services', 'App\\Entity\\Comments\\UseCase\\CreateComment', 'getCreateCommentService', true],
            'id' => ['privates', '.errored..service_locator._zxEonK.App\\Entity\\Posts\\Post', NULL, 'Cannot autowire service ".service_locator._zxEonK": it references class "App\\Entity\\Posts\\Post" but no such service exists.'],
            'postsQuery' => ['privates', 'App\\Adapter\\Post\\PostsQuery', 'getPostsQueryService', true],
        ], [
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'createComment' => 'App\\Entity\\Comments\\UseCase\\CreateComment',
            'id' => 'App\\Entity\\Posts\\Post',
            'postsQuery' => 'App\\Adapter\\Post\\PostsQuery',
        ]);
    }
}
