<?php

namespace ContainerXgjj4d9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivateControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\users\ActivateController' shared autowired service.
     *
     * @return \App\Controller\users\ActivateController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
        include_once \dirname(__DIR__, 4).'\\src\\Entity\\Users\\UseCase\\ActivateUser\\Responder.php';
        include_once \dirname(__DIR__, 4).'\\src\\Controller\\users\\ActivateController.php';

        $container->services['App\\Controller\\users\\ActivateController'] = $instance = new \App\Controller\users\ActivateController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\users\\ActivateController', $container));

        return $instance;
    }
}
