<?php

namespace ContainerXgjj4d9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommand2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RAIvUZ4.App\Entity\Comments\UseCase\CreateComment\Command' shared service.
     *
     * @return \App\Entity\Comments\UseCase\CreateComment\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.RAIvUZ4": it references class "App\\Entity\\Comments\\UseCase\\CreateComment\\Command" but no such service exists.');
    }
}
