<?php

namespace ContainerXgjj4d9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ListController' shared autowired service.
     *
     * @return \App\Controller\ListController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
        include_once \dirname(__DIR__, 4).'\\src\\Controller\\ListController.php';
        include_once \dirname(__DIR__, 4).'\\src\\Entity\\Comments\\ReadModel\\CommentsQueryInterface.php';
        include_once \dirname(__DIR__, 4).'\\src\\Adapter\\Comment\\CommentsQuery.php';

        $container->services['App\\Controller\\ListController'] = $instance = new \App\Controller\ListController(($container->privates['App\\Repository\\PostRepository'] ?? $container->load('getPostRepositoryService')), ($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService')), ($container->privates['App\\Adapter\\Post\\PostsQuery'] ?? $container->load('getPostsQueryService')), new \App\Adapter\Comment\CommentsQuery(($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService())));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\ListController', $container));

        return $instance;
    }
}
