<?php

namespace ContainerXgjj4d9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Users\RegisterType' shared autowired service.
     *
     * @return \App\Form\Users\RegisterType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\AbstractType.php';
        include_once \dirname(__DIR__, 4).'\\src\\Form\\Users\\RegisterType.php';

        return $container->privates['App\\Form\\Users\\RegisterType'] = new \App\Form\Users\RegisterType();
    }
}
