<?php

namespace ContainerROtJd6H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QRA68BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qR_a68B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qR_a68B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'post' => ['privates', '.errored..service_locator.qR_a68B.App\\Entity\\Posts\\Post', NULL, 'Cannot autowire service ".service_locator.qR_a68B": it references class "App\\Entity\\Posts\\Post" but no such service exists.'],
        ], [
            'post' => 'App\\Entity\\Posts\\Post',
        ]);
    }
}
