<?php

namespace ContainerROtJd6H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WtDaBvgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WtDaBvg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WtDaBvg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'command' => ['privates', '.errored..service_locator.WtDaBvg.App\\Entity\\Posts\\UseCase\\CreatePost\\Command', NULL, 'Cannot autowire service ".service_locator.WtDaBvg": it references class "App\\Entity\\Posts\\UseCase\\CreatePost\\Command" but no such service exists.'],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'newsCommand' => ['privates', '.errored..service_locator.WtDaBvg.App\\Entity\\Newsletter\\Newsletters\\UseCase\\SendingNewsletter\\Command', NULL, 'Cannot autowire service ".service_locator.WtDaBvg": it references class "App\\Entity\\Newsletter\\Newsletters\\UseCase\\SendingNewsletter\\Command" but no such service exists.'],
        ], [
            'command' => 'App\\Entity\\Posts\\UseCase\\CreatePost\\Command',
            'mailer' => '?',
            'newsCommand' => 'App\\Entity\\Newsletter\\Newsletters\\UseCase\\SendingNewsletter\\Command',
        ]);
    }
}
