<?php

namespace ContainerROtJd6H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F6pC2xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F_6pC2x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F_6pC2x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'command1' => ['privates', '.errored..service_locator.F_6pC2x.App\\Entity\\Newsletter\\Newsletters\\UseCase\\SendingNewsletter\\Command', NULL, 'Cannot autowire service ".service_locator.F_6pC2x": it references class "App\\Entity\\Newsletter\\Newsletters\\UseCase\\SendingNewsletter\\Command" but no such service exists.'],
            'createPost' => ['services', 'App\\Entity\\Posts\\UseCase\\CreatePost', 'getCreatePostService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'command1' => 'App\\Entity\\Newsletter\\Newsletters\\UseCase\\SendingNewsletter\\Command',
            'createPost' => 'App\\Entity\\Posts\\UseCase\\CreatePost',
            'mailer' => '?',
        ]);
    }
}
