<?php

namespace ContainerROtJd6H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.F_6pC2x.App\Entity\Newsletter\Newsletters\UseCase\SendingNewsletter\Command' shared service.
     *
     * @return \App\Entity\Newsletter\Newsletters\UseCase\SendingNewsletter\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.F_6pC2x": it references class "App\\Entity\\Newsletter\\Newsletters\\UseCase\\SendingNewsletter\\Command" but no such service exists.');
    }
}
