<?php

namespace ContainerJTxEQls;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VSqKIbbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vSqKIbb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vSqKIbb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'User' => ['services', 'App\\Adapter\\User\\Users', 'getUsersService', true],
            'activateUser' => ['services', 'App\\Entity\\Users\\UseCase\\ActivateUser', 'getActivateUserService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'User' => 'App\\Adapter\\User\\Users',
            'activateUser' => 'App\\Entity\\Users\\UseCase\\ActivateUser',
            'mailer' => '?',
        ]);
    }
}
