<?php

namespace ContainerJTxEQls;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C_VP_5mService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c.vP.5m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c.vP.5m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'User' => ['services', 'App\\Adapter\\User\\Users', 'getUsersService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'passwordChangeUser' => ['services', 'App\\Entity\\Users\\UseCase\\PasswordChangeUser', 'getPasswordChangeUserService', true],
        ], [
            'User' => 'App\\Adapter\\User\\Users',
            'mailer' => '?',
            'passwordChangeUser' => 'App\\Entity\\Users\\UseCase\\PasswordChangeUser',
        ]);
    }
}
