<?php

namespace ContainerJTxEQls;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommand9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.pBzUO1j.App\Entity\Newsletter\Newsletters\UseCase\UserJoinNewsletter\Command' shared service.
     *
     * @return \App\Entity\Newsletter\Newsletters\UseCase\UserJoinNewsletter\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.pBzUO1j": it references class "App\\Entity\\Newsletter\\Newsletters\\UseCase\\UserJoinNewsletter\\Command" but no such service exists.');
    }
}
