<?php

namespace ContainerJTxEQls;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPost2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VKJRN78.App\Entity\Posts\Post' shared service.
     *
     * @return \App\Entity\Posts\Post
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.VKJRN78": it references class "App\\Entity\\Posts\\Post" but no such service exists.');
    }
}
