<?php

namespace ContainerUlYaaJ8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ww76PDxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ww76PDx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ww76PDx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'anonJoinNewsletter' => ['services', 'App\\Entity\\Newsletter\\Newsletters\\UseCase\\AnonJoinNewsletter', 'getAnonJoinNewsletterService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'anonJoinNewsletter' => 'App\\Entity\\Newsletter\\Newsletters\\UseCase\\AnonJoinNewsletter',
            'mailer' => '?',
        ]);
    }
}
