<?php

namespace ContainerUlYaaJ8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XVXrdwTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xVXrdwT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xVXrdwT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'addLike' => ['services', 'App\\Entity\\Likes\\UseCase\\addLike', 'getAddLikeService', true],
            'id' => ['privates', '.errored..service_locator.xVXrdwT.App\\Entity\\Posts\\Post', NULL, 'Cannot autowire service ".service_locator.xVXrdwT": it references class "App\\Entity\\Posts\\Post" but no such service exists.'],
        ], [
            'addLike' => 'App\\Entity\\Likes\\UseCase\\addLike',
            'id' => 'App\\Entity\\Posts\\Post',
        ]);
    }
}
