<?php

namespace ContainerUlYaaJ8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7Xxpa8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7Xxpa_8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7Xxpa_8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'user' => ['privates', '.errored..service_locator.7Xxpa_8.App\\Entity\\Users\\User', NULL, 'Cannot autowire service ".service_locator.7Xxpa_8": it references class "App\\Entity\\Users\\User" but no such service exists.'],
        ], [
            'user' => 'App\\Entity\\Users\\User',
        ]);
    }
}
