<?php

namespace ContainerUlYaaJ8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__SkHtOfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..skHtOf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..skHtOf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'newsletter' => ['privates', '.errored..service_locator..skHtOf.App\\Entity\\Newsletter\\Newsletter', NULL, 'Cannot autowire service ".service_locator..skHtOf": it references class "App\\Entity\\Newsletter\\Newsletter" but no such service exists.'],
        ], [
            'newsletter' => 'App\\Entity\\Newsletter\\Newsletter',
        ]);
    }
}
