<?php

namespace ContainerUlYaaJ8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JBFFAEYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JBFFAEY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JBFFAEY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'command' => ['privates', '.errored..service_locator.JBFFAEY.App\\Entity\\Comments\\UseCase\\CreateComment\\Command', NULL, 'Cannot autowire service ".service_locator.JBFFAEY": it references class "App\\Entity\\Comments\\UseCase\\CreateComment\\Command" but no such service exists.'],
        ], [
            'command' => 'App\\Entity\\Comments\\UseCase\\CreateComment\\Command',
        ]);
    }
}
