<?php

namespace ContainerUlYaaJ8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8tjCUMQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8tjCUMQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8tjCUMQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'createPost' => ['services', 'App\\Entity\\Posts\\UseCase\\CreatePost', 'getCreatePostService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'createPost' => 'App\\Entity\\Posts\\UseCase\\CreatePost',
            'mailer' => '?',
        ]);
    }
}
