<?php

namespace ContainerUlYaaJ8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommand10Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.x.OS9p_.App\Entity\Likes\UseCase\unlike\Command' shared service.
     *
     * @return \App\Entity\Likes\UseCase\unlike\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.x.OS9p_": it references class "App\\Entity\\Likes\\UseCase\\unlike\\Command" but no such service exists.');
    }
}
