<?php

namespace ContainerUlYaaJ8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommand3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.J4bIjPF.App\Entity\Users\UseCase\ActivateUser\Command' shared service.
     *
     * @return \App\Entity\Users\UseCase\ActivateUser\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.J4bIjPF": it references class "App\\Entity\\Users\\UseCase\\ActivateUser\\Command" but no such service exists.');
    }
}
