<?php

namespace ContainerUlYaaJ8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommand5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QEe6iEh.App\Entity\Users\UseCase\ExpireUser\Command' shared service.
     *
     * @return \App\Entity\Users\UseCase\ExpireUser\Command
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.QEe6iEh": it references class "App\\Entity\\Users\\UseCase\\ExpireUser\\Command" but no such service exists.');
    }
}
