<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1AX8EFf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1AX8EFf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1AX8EFf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1AX8EFf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1AX8EFf\App_KernelDevDebugContainer([
    'container.build_hash' => '1AX8EFf',
    'container.build_id' => 'bb432e7b',
    'container.build_time' => 1596634536,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1AX8EFf');
