<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP00Wcts\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP00Wcts/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP00Wcts.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP00Wcts\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP00Wcts\App_KernelDevDebugContainer([
    'container.build_hash' => 'P00Wcts',
    'container.build_id' => '2841a391',
    'container.build_time' => 1661792368,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP00Wcts');
