<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJTxEQls\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJTxEQls/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJTxEQls.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJTxEQls\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJTxEQls\App_KernelDevDebugContainer([
    'container.build_hash' => 'JTxEQls',
    'container.build_id' => 'ca071853',
    'container.build_time' => 1604686208,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJTxEQls');
